package automatic.irrigation.system.enums;

public enum IrrigationStatus {

    PLOT_IRRRIGATED, PLOT_NOT_IRRIGATED, PLOT_IRRIGATION_STARTED,PLOT_IRRIGATION_NOT_STARTED,PLOT_IRRIGATION_NOT_COMPLETED,
    RETRY;
}
